### ISSUE TITLE
想学习python写签到脚本，求哪里学习好

### ISSUE THREAD

**Issue by chenlu964** [sunflo/smzdm_sign_bot#10]
大佬我想学python写签到脚本，请问一下我去什么平台或者报什么老师的课好呢，工作比较轻松，准备空闲时间学习一下，只学网页签到的编写脚本

**Comment by sunflo** [comment]
你了解了签到的原理就不会问这种问题了。

**Comment by chenlu964** [comment]
emmmm,从入门到放弃，哈哈

**Comment by sunflo** [comment]
> emmmm,从入门到放弃，哈哈

折腾吧，排除法，先学python基础肯定不会错。基础语法加网络请求。应该就能读懂别人的代码了
