### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by c26411** [sunflo/smzdm_sign_bot#11]
Traceback (most recent call last):
  File "/ql/data/scripts/sunflo_smzdm_sign_bot/smzdm_auto_sign_bot.py", line 226, in <module>
    result['data']["checkin_num"],
TypeError: list indices must be integers or slices, not str

**Comment by sunflo** [comment]
嗯，好的，我最近查下，报错，但其实应该是签到成功了把？

**Comment by c26411** [comment]
> 嗯，好的，我最近查下，报错，但其实应该是签到成功了把？

并没有

**Comment by sunflo** [comment]
嗯，石锤了，我刚刚尝试把我的cookie改错，确实是报这个错了。我挂了2个号，第一个正常
![image](https://user-images.githubusercontent.com/5946151/174213010-9dfacf52-6a7b-45c7-96f9-4e964e864420.png)

**Comment by sunflo** [comment]
> 嗯，石锤了，我刚刚尝试把我的cookie改错，确实是报这个错了。我挂了2个号，第一个正常 ![image](https://user-images.githubusercontent.com/5946151/174213010-9dfacf52-6a7b-45c7-96f9-4e964e864420.png)

这个属于异常情况处理不得当，我找时间改下，你先查下你的cookie是不是设置的不对吧

**Comment by c26411** [comment]
好嘞，我重新获取下cookie试试 ，谢谢
