### ISSUE TITLE
面板环境变量中添加，smzdm的cookie信息，key值必须是SMZDM_COOKIE

### ISSUE THREAD

**Issue by squaly1** [sunflo/smzdm_sign_bot#12]
这里填什么内容？有没有样例？在config找到这个，全部都要填吗？
__jsluid_s=xxxxxx; __ckguid=xxxxxx; device_id=xxxxxx; homepage_sug=xxxxxx; r_sort_type=xxxxxx; _zdmA.vid=xxxxxx; sajssdk_2015_cross_new_user=xxxxxx; sensorsdata2015jssdkcross=xxxxxx; footer_floating_layer=xxxxxx; ad_date=xxxxxx; ad_json_feed=xxxxxx; zdm_qd=xxxxxx; sess=xxxxxx; user=xxxxxx; _zdmA.uid=xxxxxx; smzdm_id=xxxxxx; userId=xxxxxx; bannerCounter=xxxxxx; _zdmA.time=xxxxxx;

其中：zdm_qd=xxxxxx;userId=xxxxxx; 找不到啊？

**Comment by sunflo** [comment]
见这个issue======>>>>  https://github.com/sunflo/smzdm_sign_bot/issues/2
