### ISSUE TITLE
昨天还正常，今天突然用不了咯

### ISSUE THREAD

**Issue by noir1216** [sunflo/smzdm_sign_bot#14]
## 开始执行... 2022-12-17 16:16:53

[2022-12-17 16:16:53]: 检测到1个cookie记录
开始签到
Traceback (most recent call last):
  File "/ql/data/scripts/sunflo_smzdm_sign_bot/smzdm_auto_sign_bot.py", line 226, in <module>
    result['data']["checkin_num"],
TypeError: list indices must be integers or slices, not str

## 执行结束... 2022-12-17 16:16:56  耗时 3 秒

青龙版本：2.15.3

**Comment by sunflo** [comment]
更新cookie试下，好像是有问题

**Comment by hahach** [comment]
一样的报错，有一周时间了，双十二开始的。更新了cookie没效果。比较好玩的是，手动签到后，再运行是没报错的。

**Comment by noir1216** [comment]
> 一样的报错，有一周时间了，双十二开始的。更新了cookie没效果。比较好玩的是，手动签到后，再运行是没报错的。

我没管它，好像自己好了

**Comment by sunflo** [comment]
我今天pc登录看了下

**Comment by sunflo** [comment]
> > 一样的报错，有一周时间了，双十二开始的。更新了cookie没效果。比较好玩的是，手动签到后，再运行是没报错的。
> 
> 我没管它，好像自己好了

应该是机器人校验之类的拦截了，我在公司挂着梯子pc登的zmd，登录也是报‘验证码错误’
后面弹出滑块验证通过，就签到成功了，对比下报文没找到对应的字段。这块不是特别懂，所以暂时没辙
尝试重新拨号切换ip试试

**Comment by yuxingxu** [comment]
现在pc端多了一个滑块签到

**Comment by eadorothy86** [comment]
怎样可以解决？手动签到后运行脚本就可以，直接运行脚本应该被滑块拦截了，怎样签到都签不了

**Comment by noir1216** [comment]
> 现在pc端多了一个滑块签到

不清楚怎么判定的，我手动签到也是前天有滑块，这两天又没有滑块
