### ISSUE TITLE
貌似这两天不能用了，作者那边是的么？

### ISSUE THREAD

**Issue by bubble2016** [sunflo/smzdm_sign_bot#15]
[2022-12-28 10:52:24]: 检测到1个cookie记录
开始签到
Traceback (most recent call last):
  File "/ql/data/scripts/sunflo_smzdm_sign_bot/smzdm_auto_sign_bot.py", line 226, in <module>
    result['data']["checkin_num"],
TypeError: list indices must be integers or slices, not str

**Comment by Arbre-github** [comment]
都一样。。增加了验证码了

**Comment by wanababy** [comment]
不能用了，能更新吗？

**Comment by sunflo** [comment]
刚羊完，这两天抽空在研究

**Comment by hahach** [comment]
有其它脚本作者采用的方法是useragent改为iPhone跳过验证，可以参考下

**Comment by sunflo** [comment]
> 有其它脚本作者采用的方法是useragent改为iPhone跳过验证，可以参考下

你们可以更新试下，我这边ua改成iphone我试过还是不行，你们可以尝试下

**Comment by h141242** [comment]
我这边ua改成iphone还是不行

**Comment by Arbre-github** [comment]
这个UA能不能设置成，自己手机上APP抓包的ua？

**Comment by h141242** [comment]
> 这个UA不能设置成，自己手机上APP抓包的ua？

我这用了挂包UA，iphone的UA，都不行

**Comment by hzerebus** [comment]
http://zdmclock.bitup.top/#/pages/smzdm/userclock?id=4079  大家可以试试这个。我现在用这个网页挂。还可以。

**Comment by euzenlee** [comment]
> 

从这个网站链接去的源码站，代码已经是两三年前的了，没有参考意义。
