### ISSUE TITLE
1.21失效

### ISSUE THREAD

**Issue by stnnjoe** [sunflo/smzdm_sign_bot#17]
Traceback (most recent call last):
  File "smzdm_auto_sign_bot.py", line 226, in <module>
    result['data']["checkin_num"],
TypeError: list indices must be integers or slices, not str

**Comment by euzenlee** [comment]
因为增加验证码，所以之前的操作无效了。
话说应该增加对json返回信息里err_code的判断，可以发送签到失败的信息，而不是现在这样直接抛错退出，没有后续的音信。

**Comment by sunflo** [comment]
> 有兴趣可以试试这个新的脚本，基于 App 接口的签到，并且支持抽奖做任务等功能 https://github.com/hex-ci/smzdm_script

点赞了。很6

**Comment by sunflo** [comment]
> 

请教使用什么工具抓的https包
