### ISSUE TITLE
请问cookie的字段是哪一些，一大堆不知道哪些是需要的，需要填入哪一些

### ISSUE THREAD

**Issue by Windrunner20** [sunflo/smzdm_sign_bot#2]

**Comment by Windrunner20** [comment]
这三个就够了
userCookie = "sess=xxxxxx; user=user:xxx|xxx; smzdm_id=xxx;"

**Comment by sunflo** [comment]
全部

**Comment by sunflo** [comment]
> 这三个就够了
> userCookie = "sess=xxxxxx; user=user:xxx|xxx; smzdm_id=xxx;"

好的，感谢
