### ISSUE TITLE
张大妈的cookie怎么正确获取

### ISSUE THREAD

**Issue by sxgxhk** [sunflo/smzdm_sign_bot#9]
如题，按网上的教程获取了，很长一窜，运行时报错
![errors](https://user-images.githubusercontent.com/23137510/159817190-631cf01e-1203-40e5-8866-040eae88206d.png)

**Comment by sunflo** [comment]
不用全部填的。
https://github.com/sunflo/smzdm_sign_bot/issues/2

**Comment by wanababy** [comment]
那填哪一部分的呢，里面东西很多

**Comment by sunflo** [comment]
> 那填哪一部分的呢，里面东西很多

上面不是回了么，点链接
